import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Navbar from "./components/navbar/page"; // Thêm dấu chấm phẩy ở đây
import Footer from "./components/footer/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nguyen Duong The Vi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = (
    <header>
      <nav>
        <div className=" justify-center p-4 border-b bg-slate-50">
          <div className="container mx-auto">
            <div className="flex items-center justify-center ">
              <div className="hidden md:block"></div>
              <div className="text-center">
                <div className="text-4xl uppercase">
                  Nguyen Duong The Vi Blog
                </div>
                {/* <div className="text-lg text-slate-500">
                  Friday, Nov 18,2022
                </div> */}
              </div>
            </div>
          </div>
        </div>
        <div>
          <div id="menu">
            <ul className="justify-center text-lg font-medium md:flex">
              <li className="p-3 mx-2 text-black">
                <a href="/">Home</a>
              </li>
              <li className="p-3 mx-2 text-slate-600 hover:text-black">
                <a href="/blog">Blog</a>
              </li>
              <li className="p-3 mx-2 text-slate-600 hover:text-black">
                <a href="/about">About</a>
              </li>
              <li className="p-3 mx-2 text-slate-600 hover:text-black">
                <a href="/contact">Contact</a>
              </li>
              <li className="p-3 mx-2 text-slate-600 hover:text-black">
                <a href="/project">Project</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  );
  const footer = (
    <>
      <footer>
        <div className="border-t border-slate-400 mt-12 py-6 text-center text-slate-400">
          <h3>Designed by Nguyen Duong The Vi</h3>{" "}
        </div>
      </footer>
    </>
  );

  return (
    <html>
      <head />
      <body>
        {header}
        <div className="mx-auto  max-w-8xl px-6">
          <div className="mx-auto  max-w-2xl px-6">{children}</div>
        </div>
        {footer}
      </body>
    </html>
  );
}
